# Generated by Django 4.0.3 on 2023-06-18 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carosel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/carosel/hero/')),
                ('imagename', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
