# Generated by Django 4.0.3 on 2023-06-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_aboutblocks_aboutcontent_home_homepoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villscarosel',
            name='images',
            field=models.ImageField(upload_to='images/carosel/villa/'),
        ),
    ]
